# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class McDonaldsItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    itemId = scrapy.Field()
    itemName = scrapy.Field()
    categories = scrapy.Field()
    allergens = scrapy.Field()
    menuItemNo = scrapy.Field()
    calories = scrapy.Field()
    calories_DV = scrapy.Field()
    calories_units = scrapy.Field()
    calories_from_fat = scrapy.Field()
    calories_from_fat_DV = scrapy.Field()
    calories_from_fat_units = scrapy.Field()
    energy_kJ = scrapy.Field()
    energy_kJ_DV = scrapy.Field()
    energy_kJ_units = scrapy.Field()
    protein = scrapy.Field()
    protein_DV = scrapy.Field()
    protein_units = scrapy.Field()
    carbohydrate = scrapy.Field()
    carbohydrate_DV = scrapy.Field()
    carbohydrate_units = scrapy.Field()
    fibre = scrapy.Field()
    fibre_DV = scrapy.Field()
    fibre_units = scrapy.Field()
    sugars = scrapy.Field()
    sugars_DV = scrapy.Field()
    sugars_units = scrapy.Field()
    addedsugars = scrapy.Field()
    addedsugars_DV = scrapy.Field()
    addedsugars_units = scrapy.Field()
    fat = scrapy.Field()
    fat_DV = scrapy.Field()
    fat_units = scrapy.Field()
    saturated_fat = scrapy.Field()
    saturated_fat_DV = scrapy.Field()
    saturated_fat_units = scrapy.Field()
    trans_fat = scrapy.Field()
    trans_fat_DV = scrapy.Field()
    trans_fat_units = scrapy.Field()
    cholesterol = scrapy.Field()
    cholesterol_DV = scrapy.Field()
    cholesterol_units = scrapy.Field()
    vitaminB6 = scrapy.Field()
    vitaminB6_DV = scrapy.Field()
    vitaminB6_units = scrapy.Field()
    vitaminD = scrapy.Field()
    vitaminD_DV = scrapy.Field()
    vitaminD_units = scrapy.Field()
    calcium = scrapy.Field()
    calcium_DV = scrapy.Field()
    calcium_units = scrapy.Field()
    iron = scrapy.Field()
    iron_DV = scrapy.Field()
    iron_units = scrapy.Field()
    phosphorus = scrapy.Field()
    phosphorus_DV = scrapy.Field()
    phosphorus_units = scrapy.Field()
    potassium = scrapy.Field()
    potassium_DV = scrapy.Field()
    potassium_units = scrapy.Field()
    sodium = scrapy.Field()
    sodium_DV = scrapy.Field()
    sodium_units = scrapy.Field()
    caffeine = scrapy.Field()
    caffeine_DV = scrapy.Field()
    caffeine_units = scrapy.Field()
    itemIngredientStatement = scrapy.Field()
